### PR TITLE
Create Jupyter Notebook for Tutorial

### PR DESCRIPTION
**Pull request by LimberenceCheng**
Create Jupyter Notebook for Tutorial example.

### CODE REVIEW

**Comment by zsdonghao** [comment]
hi @LimberenceCheng , what is the purpose of this PR?

**Comment by LimberenceCheng** [comment]
I am about to make jupyter notebook for the example so it could look better, can I contribute my work to TensorLayer? Coz I really love your work.

**Comment by zsdonghao** [comment]
Cool, but this PR seem to be a unfinished work, can you finish all of it and push it again?
Alternative option is to make your own repository, then I can link TL repository to it.

**Comment by LimberenceCheng** [comment]
Of course, I will make another PR as I finish my job. thx.

**Comment by zsdonghao** [comment]
@LimberenceCheng , feel free to reopen it if necessary. if you like, you can create your own repo, then I can put a link in this repo.

**Pull request closed without merging**
