### PR TITLE
Update nlp.py

### PR DESCRIPTION
**Pull request by todtom**
Fix some bugs like https://github.com/tensorflow/tensorflow/issues/5118.

### CODE REVIEW

**Comment by todtom** [comment]
I run it for the Chinese-English translation task. When use 'basic_tokenizer' it often reports the error like 'TypeError: cannot use a bytes pattern on a string-like object'. It worksfor me after fix the bugs. I'm not sure whether the modified 'initital_vocabulary'  works for some other tokenizers

**Comment by zsdonghao** [comment]
@todtom Hi, thank you for your contribution. I wonder which TF version are you using? As the code seem to work fine previously, we need to make sure other users can also run their scripts. Thanks~

**Comment by wagamamaz** [comment]
@todtom after you fix the bugs, can it work well in English-French translation task?

**Comment by todtom** [comment]
@zsdonghao the enviroment as follows:

> Windows10, python 3.5.2.3, tensorflow 0.12.0, tensorlayer 1.2.8

maybe the error caused by system? I haven't run it in Linux yet
@wagamamaz I train a toy 'en-fr' model which use 1k sentences for training data, it seems work well.

**Comment by zsdonghao** [comment]
@todtom great, it may caused by python3.5.

**Pull request merged**
