### PR TITLE
Added download utility function : maybe_download_and_extract()

### PR DESCRIPTION
**Pull request by JoelKronander**
Added a download utility function in files.py, maybe_download_and_extract, that tries to find filename in working_dir otherwise downloads with progress bar and optionally extracts .tar and .zip files. 

Also updated the tutorial_vgg16 example to use the new function.
Several dataset loaders in files could also adapt the new function for improved consistency.

### CODE REVIEW

**Comment by zsdonghao** [comment]
@JoelKronander could we simplify the args of function ? e.g. use `format='zip'` instead of `is_tar, is_zip`? do you think it is better?

**Comment by JoelKronander** [comment]
Just updated a new version with an optional extract=True/False option. If set to True, detects if .tar or .zip files and uncompresses.

**Comment by JoelKronander** [comment]
Is something like this interface what you had in mind? Or should I change it to something else?
I could also clean up some code in the files.py to use this new function instead of repeated definitions of private download functions if you like.

**Comment by boscotsang** [comment]
I've adding the path argument to the load dataset functions. I think you can replace the origin download and extract function with your maybe_download_and_extract() function.

**Comment by JoelKronander** [comment]
superceded by PR#72

**Pull request closed without merging**
